apiVersion: v1
kind: Service
metadata:
 name: ot-pasco-product-web-svc-dev
 namespace: dev
 labels:
   app: ncnpasco-product-web-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 31199
   targetPort: 31199
 selector:
   app: ncnpasco-product-web-dev
