kind: PersistentVolume
apiVersion: v1
metadata:
  name: apacheentity-management-dev
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default-storage-class-1
  persistentVolumeReclaimPolicy: Delete
