apiVersion: v1
kind: Service
metadata:
 name: ot-pasco-subscription-web-svc-dev
 namespace: dev
 labels:
   app: ncnpasco-subscription-web-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 31193
   targetPort: 31193
 selector:
   app: ncnpasco-subscription-web-dev
