apiVersion: v1
kind: Service
metadata:
 name: ot-php-web-ms-svc-dev
 namespace: dev
 labels:
   app: php-web-ms-dev
spec:
 type: LoadBalancer
 ports:
 - name: http
   protocol: TCP
   port: 80
   targetPort: 80
 selector:
   app: php-web-ms-dev
