apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emailattachsubscription-dev0-nfs
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: emailattachsubscription-dev0-nfs
