kind: PersistentVolume
apiVersion: v1
metadata:
  name: webms-download-dev-nfs
  namespace: dev
  labels:
    app: webms-download-dev-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.71.96.72
    path: "/var/log/php/download/webms"

