kind: PersistentVolume
apiVersion: v1
metadata:
  name: reports-excel-nfs
  namespace: dev
  labels:
    app: reports-excel-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.71.96.72
    path: "/var/log/php/reports/public/excel"

