kind: PersistentVolume
apiVersion: v1
metadata:
  name: webms-uploads-dev-nfs
  namespace: dev
  labels:
    app: webms-uploads-dev-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.71.96.72
    path: "/var/log/php/webms/public/uploads"

