apiVersion: v1
kind: Service
metadata:
 name: ot-java-config-server-svc-dev
 namespace: dev
 labels:
   app: ncn-java-config-server-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 9296
   targetPort: 9296
 selector:
   app: ncn-java-config-server-dev
