apiVersion: v1
kind: Service
metadata:
 name: ot-pasco-partner-web-svc-dev
 namespace: dev
 labels:
   app: ncnpasco-partner-web-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 31198
   targetPort: 31198
 selector:
   app: ncnpasco-partner-web-dev
