apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webms-download-dev-nfs
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: webms-download-dev-nfs
