apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logfilecustomer-dev-nfs
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: logfilecustomer-dev-nfs
