apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logfile-vac-dev-nfs
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: logfile-vac-dev-nfs
