kind: PersistentVolume
apiVersion: v1
metadata:
  name: apache-subscription-dev-nfs
  namespace: dev
  labels:
    app: apache-subscription-dev-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.71.96.72
    path: "/var/log/php/apache/subscription"
