apiVersion: v1
kind: Service
metadata:
 name: ot-java-pasco-contact-web-svc-dev
 namespace: dev
 labels:
   app: java-pasco-contact-web-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 31196
   targetPort: 31196
 selector:
   app: java-pasco-contact-web-dev
