apiVersion: v1
kind: Service
metadata:
 name: ot-php-subscription-svc-dev
 namespace: dev
 labels:
   app: php-subscription-dev
spec:
 type: ClusterIP
 ports:
 - name: http
   protocol: TCP
   port: 80
   targetPort: 80
 selector:
   app: php-subscription-dev
