apiVersion: apps/v1
kind: Deployment
metadata:
  name: ot-zipkin-deployment-dev
  namespace: dev
  labels:
    app: ncnzipkin-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ncnzipkin-dev
  template:
    metadata:
      labels:
        app: ncnzipkin-dev
    spec:
      affinity:  # Add anti-affinity rule
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ncnzipkin-dev
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: false
      imagePullSecrets:
        - name: my-registry-key1
      containers:
        - name: ncn-zipkin-dev
          image: newcloudnetworks/dev-java-zipkin:ot-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
          securityContext:
            capabilities:
              drop:
                - "ALL"
              add:
                - NET_ADMIN  # Add the NET_ADMIN capability
                - CHOWN      # Add the CHOWN capability
                - FOWNER
                - DAC_OVERRIDE
                - DAC_READ_SEARCH
                - SETGID
                - SETUID
                - SYS_CHROOT
                - SYS_NICE
                - SYS_RESOURCE
                - NET_BIND_SERVICE
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.25"
              memory: "512Mi"
