apiVersion: v1
kind: Service
metadata:
 name: otzipkin-svc-dev
 namespace: dev
 labels:
   app: ncnzipkin-dev
spec:
 type: LoadBalancer  # Change this from NodePort to LoadBalancer
 ports:
 - name: http
   protocol: TCP
   port: 9411
   targetPort: 9411
 selector:
   app: ncnzipkin-dev
