apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki-loki-distributed-gateway:3100/loki/api/v1/push
    scrape_configs:
      - job_name: system
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log
      - job_name: dev-entity-management-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-entity-management-php-log
            __path__: /var/log/php/apache/entity-management/*.log
      - job_name: dev-reports-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-reports-php-log
            __path__: /var/log/php/apache/reports/*.log
      - job_name: dev-setting-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-settings-php-log
            __path__: /var/log/php/apache/settings/*.log
      - job_name: dev-subscription-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-subscription-php-log
            __path__: /var/log/php/apache/subscription/*.log
      - job_name: dev-vac-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-vac-php-log
            __path__: /var/log/php/apache/vac/*.log
      - job_name: dev-vbo-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-vbo-php-log
            __path__: /var/log/php/apache/vbo/*.log
      - job_name: dev-contact-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-contact-java-log
            __path__: /var/log/java/contact/*.log
      - job_name: dev-customer-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-customer-java-log
            __path__: /var/log/java/customer/*.log
      - job_name: dev-partner-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-partner-java-log
            __path__: /var/log/java/partner/*.log
      - job_name: dev-product-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-product-java-log
            __path__: /var/log/java/product/*.log
      - job_name: dev-subscription-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-subscription-java-log
            __path__: /var/log/java/subscription/*.log
