---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    group: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: promtail
    group: grafana
  name: promtail
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods  
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app: promtail
    group: grafana
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: promtail
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    group: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
      group: grafana
  template:
    metadata:
      labels:
        app: promtail
        group: grafana
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:make-images-static-26a87c9
          imagePullPolicy: Always
          args: ["-config.file=/etc/promtail/promtail-config.yaml"]
          volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: javalog
            mountPath: /var/log/java
            readOnly: true
          - name: phplog
            mountPath: /var/log/php/apache
            readOnly: true
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: javalog
          hostPath:
            path: /var/log/java
        - name: phplog
          hostPath:
            path: /var/log/php/apache
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 0
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    client:
      url: http://loki-loki-distributed-gateway/loki/api/v1/push


    scrape_configs:
      - job_name: system
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log
      - job_name: dev-entity-management-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-entity-management-php-log
            __path__: /var/log/php/apache/entity-management/*.log
      - job_name: dev-reports-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-reports-php-log
            __path__: /var/log/php/apache/reports/*.log
      - job_name: dev-setting-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-settings-php-log
            __path__: /var/log/php/apache/settings/*.log
      - job_name: dev-subscription-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-subscription-php-log
            __path__: /var/log/php/apache/subscription/*.log
      - job_name: dev-vac-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-vac-php-log
            __path__: /var/log/php/apache/vac/*.log
      - job_name: dev-vbo-php-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-vbo-php-log
            __path__: /var/log/php/apache/vbo/*.log
      - job_name: dev-contact-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-contact-java-log
            __path__: /var/log/java/contact/*.log
      - job_name: dev-customer-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-customer-java-log
            __path__: /var/log/java/customer/*.log
      - job_name: dev-partner-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-partner-java-log
            __path__: /var/log/java/partner/*.log
      - job_name: dev-product-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-product-java-log
            __path__: /var/log/java/product/*.log
      - job_name: dev-subscription-java-log
        static_configs:
        - targets:
            - localhost
          labels:
            job: dev-subscription-java-log
            __path__: /var/log/java/subscription/*.log
