kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logfilecontact-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: logfilecontact-dev 
  resources:
    requests:
      storage: 1Gi



