kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logfile-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: logfile-dev 
  resources:
    requests:
      storage: 2Gi
