kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logfilevac-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: logfilevac-dev
  resources:
    requests:
      storage: 1Gi

