kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subscription-excel
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: subscription-excel
  resources:
    requests:
      storage: 1Gi
