kind: PersistentVolume
apiVersion: v1
metadata:
  name: logfile-dev
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: logfile-dev
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/java/log"
