kind: PersistentVolume
apiVersion: v1
metadata:
  name: logfilesubscription-dev
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: logfilesubscription-dev
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/var/log/java/subscription"
