kind: PersistentVolume
apiVersion: v1
metadata:
  name: reports-excel
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: reports-excel
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/var/log/php/reports-service/public/excel"
