kind: PersistentVolume
apiVersion: v1
metadata:
  name: apachereports-dev
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: apachereports-dev
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/var/log/php/apache/reports"
