kind: PersistentVolume
apiVersion: v1
metadata:
  name: subscription-excel
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: subscription-excel
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/var/log/php/subscription/public/excel"
