kind: PersistentVolume
apiVersion: v1
metadata:
  name: emailattachsubscription-dev0
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: emailattachsubscription-dev0
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/opt/media/email/attachments"
