kind: PersistentVolume
apiVersion: v1
metadata:
  name: tmpfile-dev
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: tmpfile-dev
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/log"
