kind: PersistentVolume
apiVersion: v1
metadata:
  name: webms-uploads-dev
  namespace: dev
  labels:
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: webms-uploads-dev
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/var/log/php/web-ms/public/uploads"
